version: "3.7"

services:
  test-postgres-db:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: test-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    networks:
      - postgres
    command: postgres -c wal_level=logical -c max_replication_slots=10 -c max_wal_senders=10

networks:
  postgres:
    driver: bridge
    name: postgres